### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by dozortsev** [dozortsev/dozortsev.github.io#5]
Like [this portfolios](https://www.behance.net/gallery/21121127/Portfolio-Redesign-) for Designers

**Comment by dozortsev** [comment]
Add dots to on background like notebook http://www.g-a.co.nz/ jsfiddle: https://jsfiddle.net/leaverou/RtGsM/

```css
#content {
    height: 100%;
    width: 100%;

    background: radial-gradient(black 15%, transparent 15%),
                radial-gradient(black 15%, transparent 15%),
                transparent;
    background:
            -moz-radial-gradient(black 15%, transparent 15%),
            -moz-radial-gradient(black 15%, transparent 15%),
            transparent;
    background:
            -webkit-radial-gradient(black 15%, transparent 15%),
            -webkit-radial-gradient(black 15%, transparent 15%),
            transparent;
    background-position: 100px 100px, 0 0;

    -webkit-background-size:10px 10px;
    -moz-background-size:10px 10px;
    background-size: 10px 10px;
}
```
